IF DB_ID('PHANMEMTHITN') IS NULL CREATE DATABASE [PHANMEMTHITN]
GO

USE PHANMEMTHITN
GO

CREATE TABLE SINHVIEN
(
	ID INT IDENTITY (1,1),
	MASV VARCHAR(15) PRIMARY KEY,
	LOP VARCHAR(10) NOT NULL,
	TENSV NVARCHAR(50) NOT NULL,
	NGAYSINH DATE NOT NULL,
)
GO

CREATE TABLE GIANGVIEN 
(
	ID INT IDENTITY(1,1),
	MAGV VARCHAR(15) PRIMARY KEY ,
	TENGV NVARCHAR(50) NOT NULL,
	NGAYSINH DATE NOT NULL
)
GO

CREATE TABLE QUANTRI
(
	ID INT IDENTITY(1,1),
	MAQT VARCHAR(15) PRIMARY KEY,
	TENQT NVARCHAR(50) NOT NULL,
	NGAYSINH DATE NOT NULL,
)
GO

CREATE TABLE MONTHI
(
	IDMONTHI INT IDENTITY(1,1),
	MAMT VARCHAR(15) PRIMARY KEY,
	TENMT NVARCHAR(50),
	

)
GO

CREATE TABLE DANHMUCCAUHOI
(
	IDDANHMUC INT IDENTITY(1,1) PRIMARY KEY,
	MAMT VARCHAR(15) FOREIGN KEY REFERENCES MONTHI(MAMT) ON UPDATE CASCADE
)
GO


CREATE TABLE CAUHOI
(
	IDCAUHOI INT IDENTITY(1,1) PRIMARY KEY,
	NDCAUHOI NVARCHAR(500),
	DAPAN1 NVARCHAR NOT NULL, 
	DAPAN2 NVARCHAR NOT NULL,	
	DAPAN3 NVARCHAR NOT NULL,
	DAPAN4 NVARCHAR NOT NULL,
	DAPANDUNG NVARCHAR NOT NULL,
	IDDANHMUC INT FOREIGN KEY REFERENCES DANHMUCCAUHOI(IDDANHMUC) ON UPDATE CASCADE
)
GO

CREATE TABLE DETHI
(
	ID INT IDENTITY(1,1),
	MADETHI VARCHAR(10) PRIMARY KEY,
)
GO



CREATE TABLE KITHI
(
	ID INT IDENTITY(1,1),
	MAKITHI VARCHAR(10) PRIMARY KEY,
	TENKITHI NVARCHAR(50)
)
GO

CREATE TABLE CHITIETKITHI
(
	NGAYTHI DATE,
	THOIGIANTHI DATETIME,
)
GO


CREATE TABLE BANGDIEM
(
	ID INT IDENTITY(1,1),
	MABD VARCHAR(10) PRIMARY KEY,
	TENBD NVARCHAR(50),
)
GO
