//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemThiTracNghiem.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANGDIEM
    {
        public Nullable<int> ID { get; set; }
        public Nullable<double> DIEM { get; set; }
        public string MASV { get; set; }
        public string MAKITHI { get; set; }
        public string MAMT { get; set; }
    
        public virtual CHITIETKYTHI CHITIETKYTHI { get; set; }
    }
}
