//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemThiTracNghiem.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAUHOI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAUHOI()
        {
            this.CHITIETDETHIs = new HashSet<CHITIETDETHI>();
        }
    
        public int STT { get; set; }
        public int MACAUHOI { get; set; }
        public string NDCAUHOI { get; set; }
        public string DAPAN1 { get; set; }
        public string DAPAN2 { get; set; }
        public string DAPAN3 { get; set; }
        public string DAPAN4 { get; set; }
        public string DAPANDUNG { get; set; }
        public string MAGV { get; set; }
        public string MAMT { get; set; }
    
        public virtual GIANGVIEN GIANGVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDETHI> CHITIETDETHIs { get; set; }
    }
}
