//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemThiTracNghiem.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETKYTHI
    {
        public string MAKITHI { get; set; }
        public string MAMT { get; set; }
        public Nullable<double> DIEM { get; set; }
        public Nullable<int> THOIGIANTHI { get; set; }
        public Nullable<System.DateTime> THOIGIANBD { get; set; }
        public Nullable<System.DateTime> THOIGIANKT { get; set; }
        public string MASV { get; set; }
    
        public virtual BANGDIEM BANGDIEM { get; set; }
        public virtual KITHI KITHI { get; set; }
        public virtual MONTHI MONTHI { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
