//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemThiTracNghiem.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KITHI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KITHI()
        {
            this.CHITIETKYTHIs = new HashSet<CHITIETKYTHI>();
        }
    
        public Nullable<int> ID { get; set; }
        public string MAKITHI { get; set; }
        public string TENKITHI { get; set; }
        public string ADMIN { get; set; }
        public Nullable<System.DateTime> THOIGIANBDKITHI { get; set; }
        public Nullable<System.DateTime> THOIGIANKTKITHI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETKYTHI> CHITIETKYTHIs { get; set; }
        public virtual QUANTRI QUANTRI { get; set; }
    }
}
