//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemThiTracNghiem.DAL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PHANMEMTHITRACNGHIEMEntities : DbContext
    {
        public PHANMEMTHITRACNGHIEMEntities()
            : base("name=PHANMEMTHITRACNGHIEMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BANGDIEM> BANGDIEMs { get; set; }
        public virtual DbSet<CAUHOI> CAUHOIs { get; set; }
        public virtual DbSet<CHITIETDETHI> CHITIETDETHIs { get; set; }
        public virtual DbSet<CHITIETKYTHI> CHITIETKYTHIs { get; set; }
        public virtual DbSet<DETHI> DETHIs { get; set; }
        public virtual DbSet<GIANGVIEN> GIANGVIENs { get; set; }
        public virtual DbSet<KITHI> KITHIs { get; set; }
        public virtual DbSet<MONTHI> MONTHIs { get; set; }
        public virtual DbSet<QUANTRI> QUANTRIs { get; set; }
        public virtual DbSet<SINHVIEN> SINHVIENs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
